name: Build Yaak Plugin

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup Node (for NPM)
        uses: actions/setup-node@v7
        with:
          node-version: '24' # Yaak CLI requires Node.js 24+

      - name: Install dependencies
        run: |
          npm install
          npm install -g @yaakapp/cli

      - name: Build plugin
        run: yaak plugin build

      - name: Upload build results
        uses: actions/upload-artifact@v7
        with:
          name: yaak-plugin.zip
          path: |
            dist/
            build/
            *.js
            package.json
